/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as guestLayoutRouteImport } from './routes/(guest)/layout'
import { Route as protectedLayoutRouteImport } from './routes/(protected)/layout'
import { Route as guestForgotPasswordPageRouteImport } from './routes/(guest)/forgot-password/page'
import { Route as guestLoginPageRouteImport } from './routes/(guest)/login/page'
import { Route as guestResetPasswordPageRouteImport } from './routes/(guest)/reset-password/page'
import { Route as protecteddashboardPageRouteImport } from './routes/(protected)/(dashboard)/page'
import { Route as protectedAdminsPageRouteImport } from './routes/(protected)/admins/page'
import { Route as protectedFirmsPageRouteImport } from './routes/(protected)/firms/page'
import { Route as protectedAdminsAdminIdPageRouteImport } from './routes/(protected)/admins/$adminId/page'
import { Route as protectedAdminsNewPageRouteImport } from './routes/(protected)/admins/new/page'
import { Route as protectedAdminsAdminIdEditPageRouteImport } from './routes/(protected)/admins/$adminId/edit/page'

const guestLayoutRoute = guestLayoutRouteImport.update({
  id: '/(guest)',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedLayoutRoute = protectedLayoutRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const guestForgotPasswordPageRoute = guestForgotPasswordPageRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => guestLayoutRoute,
} as any)
const guestLoginPageRoute = guestLoginPageRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => guestLayoutRoute,
} as any)
const guestResetPasswordPageRoute = guestResetPasswordPageRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => guestLayoutRoute,
} as any)
const protecteddashboardPageRoute = protecteddashboardPageRouteImport.update({
  id: '/(dashboard)/',
  path: '/',
  getParentRoute: () => protectedLayoutRoute,
} as any)
const protectedAdminsPageRoute = protectedAdminsPageRouteImport.update({
  id: '/admins/',
  path: '/admins/',
  getParentRoute: () => protectedLayoutRoute,
} as any)
const protectedFirmsPageRoute = protectedFirmsPageRouteImport.update({
  id: '/firms/',
  path: '/firms/',
  getParentRoute: () => protectedLayoutRoute,
} as any)
const protectedAdminsAdminIdPageRoute =
  protectedAdminsAdminIdPageRouteImport.update({
    id: '/admins/$adminId/',
    path: '/admins/$adminId/',
    getParentRoute: () => protectedLayoutRoute,
  } as any)
const protectedAdminsNewPageRoute = protectedAdminsNewPageRouteImport.update({
  id: '/admins/new/',
  path: '/admins/new/',
  getParentRoute: () => protectedLayoutRoute,
} as any)
const protectedAdminsAdminIdEditPageRoute =
  protectedAdminsAdminIdEditPageRouteImport.update({
    id: '/admins/$adminId/edit/',
    path: '/admins/$adminId/edit/',
    getParentRoute: () => protectedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/forgot-password/': typeof guestForgotPasswordPageRoute
  '/login/': typeof guestLoginPageRoute
  '/reset-password/': typeof guestResetPasswordPageRoute
  '/': typeof protecteddashboardPageRoute
  '/admins/': typeof protectedAdminsPageRoute
  '/firms/': typeof protectedFirmsPageRoute
  '/admins/$adminId/': typeof protectedAdminsAdminIdPageRoute
  '/admins/new/': typeof protectedAdminsNewPageRoute
  '/admins/$adminId/edit/': typeof protectedAdminsAdminIdEditPageRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof guestForgotPasswordPageRoute
  '/login': typeof guestLoginPageRoute
  '/reset-password': typeof guestResetPasswordPageRoute
  '/': typeof protecteddashboardPageRoute
  '/admins': typeof protectedAdminsPageRoute
  '/firms': typeof protectedFirmsPageRoute
  '/admins/$adminId': typeof protectedAdminsAdminIdPageRoute
  '/admins/new': typeof protectedAdminsNewPageRoute
  '/admins/$adminId/edit': typeof protectedAdminsAdminIdEditPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(guest)': typeof guestLayoutRouteWithChildren
  '/(protected)': typeof protectedLayoutRouteWithChildren
  '/(guest)/forgot-password/': typeof guestForgotPasswordPageRoute
  '/(guest)/login/': typeof guestLoginPageRoute
  '/(guest)/reset-password/': typeof guestResetPasswordPageRoute
  '/(protected)/(dashboard)/': typeof protecteddashboardPageRoute
  '/(protected)/admins/': typeof protectedAdminsPageRoute
  '/(protected)/firms/': typeof protectedFirmsPageRoute
  '/(protected)/admins/$adminId/': typeof protectedAdminsAdminIdPageRoute
  '/(protected)/admins/new/': typeof protectedAdminsNewPageRoute
  '/(protected)/admins/$adminId/edit/': typeof protectedAdminsAdminIdEditPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/forgot-password/'
    | '/login/'
    | '/reset-password/'
    | '/'
    | '/admins/'
    | '/firms/'
    | '/admins/$adminId/'
    | '/admins/new/'
    | '/admins/$adminId/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/'
    | '/admins'
    | '/firms'
    | '/admins/$adminId'
    | '/admins/new'
    | '/admins/$adminId/edit'
  id:
    | '__root__'
    | '/(guest)'
    | '/(protected)'
    | '/(guest)/forgot-password/'
    | '/(guest)/login/'
    | '/(guest)/reset-password/'
    | '/(protected)/(dashboard)/'
    | '/(protected)/admins/'
    | '/(protected)/firms/'
    | '/(protected)/admins/$adminId/'
    | '/(protected)/admins/new/'
    | '/(protected)/admins/$adminId/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  guestLayoutRoute: typeof guestLayoutRouteWithChildren
  protectedLayoutRoute: typeof protectedLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(guest)': {
      id: '/(guest)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof guestLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(guest)/forgot-password/': {
      id: '/(guest)/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof guestForgotPasswordPageRouteImport
      parentRoute: typeof guestLayoutRoute
    }
    '/(guest)/login/': {
      id: '/(guest)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof guestLoginPageRouteImport
      parentRoute: typeof guestLayoutRoute
    }
    '/(guest)/reset-password/': {
      id: '/(guest)/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof guestResetPasswordPageRouteImport
      parentRoute: typeof guestLayoutRoute
    }
    '/(protected)/(dashboard)/': {
      id: '/(protected)/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protecteddashboardPageRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/admins/': {
      id: '/(protected)/admins/'
      path: '/admins'
      fullPath: '/admins/'
      preLoaderRoute: typeof protectedAdminsPageRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/firms/': {
      id: '/(protected)/firms/'
      path: '/firms'
      fullPath: '/firms/'
      preLoaderRoute: typeof protectedFirmsPageRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/admins/$adminId/': {
      id: '/(protected)/admins/$adminId/'
      path: '/admins/$adminId'
      fullPath: '/admins/$adminId/'
      preLoaderRoute: typeof protectedAdminsAdminIdPageRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/admins/new/': {
      id: '/(protected)/admins/new/'
      path: '/admins/new'
      fullPath: '/admins/new/'
      preLoaderRoute: typeof protectedAdminsNewPageRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/admins/$adminId/edit/': {
      id: '/(protected)/admins/$adminId/edit/'
      path: '/admins/$adminId/edit'
      fullPath: '/admins/$adminId/edit/'
      preLoaderRoute: typeof protectedAdminsAdminIdEditPageRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
  }
}

interface guestLayoutRouteChildren {
  guestForgotPasswordPageRoute: typeof guestForgotPasswordPageRoute
  guestLoginPageRoute: typeof guestLoginPageRoute
  guestResetPasswordPageRoute: typeof guestResetPasswordPageRoute
}

const guestLayoutRouteChildren: guestLayoutRouteChildren = {
  guestForgotPasswordPageRoute: guestForgotPasswordPageRoute,
  guestLoginPageRoute: guestLoginPageRoute,
  guestResetPasswordPageRoute: guestResetPasswordPageRoute,
}

const guestLayoutRouteWithChildren = guestLayoutRoute._addFileChildren(
  guestLayoutRouteChildren,
)

interface protectedLayoutRouteChildren {
  protecteddashboardPageRoute: typeof protecteddashboardPageRoute
  protectedAdminsPageRoute: typeof protectedAdminsPageRoute
  protectedFirmsPageRoute: typeof protectedFirmsPageRoute
  protectedAdminsAdminIdPageRoute: typeof protectedAdminsAdminIdPageRoute
  protectedAdminsNewPageRoute: typeof protectedAdminsNewPageRoute
  protectedAdminsAdminIdEditPageRoute: typeof protectedAdminsAdminIdEditPageRoute
}

const protectedLayoutRouteChildren: protectedLayoutRouteChildren = {
  protecteddashboardPageRoute: protecteddashboardPageRoute,
  protectedAdminsPageRoute: protectedAdminsPageRoute,
  protectedFirmsPageRoute: protectedFirmsPageRoute,
  protectedAdminsAdminIdPageRoute: protectedAdminsAdminIdPageRoute,
  protectedAdminsNewPageRoute: protectedAdminsNewPageRoute,
  protectedAdminsAdminIdEditPageRoute: protectedAdminsAdminIdEditPageRoute,
}

const protectedLayoutRouteWithChildren = protectedLayoutRoute._addFileChildren(
  protectedLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  guestLayoutRoute: guestLayoutRouteWithChildren,
  protectedLayoutRoute: protectedLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
