/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as protectedLayoutRouteImport } from './routes/(protected)/layout'
import { Route as guestLayoutRouteImport } from './routes/(guest)/layout'
import { Route as protecteddashboardPageRouteImport } from './routes/(protected)/(dashboard)/page'
import { Route as guestLoginPageRouteImport } from './routes/(guest)/login/page'

const protectedLayoutRoute = protectedLayoutRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const guestLayoutRoute = guestLayoutRouteImport.update({
  id: '/(guest)',
  getParentRoute: () => rootRouteImport,
} as any)
const protecteddashboardPageRoute = protecteddashboardPageRouteImport.update({
  id: '/(dashboard)/',
  path: '/',
  getParentRoute: () => protectedLayoutRoute,
} as any)
const guestLoginPageRoute = guestLoginPageRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => guestLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login/': typeof guestLoginPageRoute
  '/': typeof protecteddashboardPageRoute
}
export interface FileRoutesByTo {
  '/login': typeof guestLoginPageRoute
  '/': typeof protecteddashboardPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(guest)': typeof guestLayoutRouteWithChildren
  '/(protected)': typeof protectedLayoutRouteWithChildren
  '/(guest)/login/': typeof guestLoginPageRoute
  '/(protected)/(dashboard)/': typeof protecteddashboardPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login/' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/'
  id:
    | '__root__'
    | '/(guest)'
    | '/(protected)'
    | '/(guest)/login/'
    | '/(protected)/(dashboard)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  guestLayoutRoute: typeof guestLayoutRouteWithChildren
  protectedLayoutRoute: typeof protectedLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(guest)': {
      id: '/(guest)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof guestLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/(dashboard)/': {
      id: '/(protected)/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protecteddashboardPageRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(guest)/login/': {
      id: '/(guest)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof guestLoginPageRouteImport
      parentRoute: typeof guestLayoutRoute
    }
  }
}

interface guestLayoutRouteChildren {
  guestLoginPageRoute: typeof guestLoginPageRoute
}

const guestLayoutRouteChildren: guestLayoutRouteChildren = {
  guestLoginPageRoute: guestLoginPageRoute,
}

const guestLayoutRouteWithChildren = guestLayoutRoute._addFileChildren(
  guestLayoutRouteChildren,
)

interface protectedLayoutRouteChildren {
  protecteddashboardPageRoute: typeof protecteddashboardPageRoute
}

const protectedLayoutRouteChildren: protectedLayoutRouteChildren = {
  protecteddashboardPageRoute: protecteddashboardPageRoute,
}

const protectedLayoutRouteWithChildren = protectedLayoutRoute._addFileChildren(
  protectedLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  guestLayoutRoute: guestLayoutRouteWithChildren,
  protectedLayoutRoute: protectedLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
