/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as adminLayoutRouteImport } from './routes/(admin)/layout'
import { Route as LoginPageRouteImport } from './routes/login/page'
import { Route as admindashboardPageRouteImport } from './routes/(admin)/(dashboard)/page'

const adminLayoutRoute = adminLayoutRouteImport.update({
  id: '/(admin)',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPageRoute = LoginPageRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const admindashboardPageRoute = admindashboardPageRouteImport.update({
  id: '/(dashboard)/',
  path: '/',
  getParentRoute: () => adminLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login/': typeof LoginPageRoute
  '/': typeof admindashboardPageRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginPageRoute
  '/': typeof admindashboardPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(admin)': typeof adminLayoutRouteWithChildren
  '/login/': typeof LoginPageRoute
  '/(admin)/(dashboard)/': typeof admindashboardPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login/' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/'
  id: '__root__' | '/(admin)' | '/login/' | '/(admin)/(dashboard)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  adminLayoutRoute: typeof adminLayoutRouteWithChildren
  LoginPageRoute: typeof LoginPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(admin)': {
      id: '/(admin)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof adminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)/(dashboard)/': {
      id: '/(admin)/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof admindashboardPageRouteImport
      parentRoute: typeof adminLayoutRoute
    }
  }
}

interface adminLayoutRouteChildren {
  admindashboardPageRoute: typeof admindashboardPageRoute
}

const adminLayoutRouteChildren: adminLayoutRouteChildren = {
  admindashboardPageRoute: admindashboardPageRoute,
}

const adminLayoutRouteWithChildren = adminLayoutRoute._addFileChildren(
  adminLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  adminLayoutRoute: adminLayoutRouteWithChildren,
  LoginPageRoute: LoginPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
