/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as guestLayoutRouteImport } from './routes/(guest)/layout'
import { Route as privateLayoutRouteImport } from './routes/(private)/layout'
import { Route as privatePageRouteImport } from './routes/(private)/page'
import { Route as privateoperationsLayoutRouteImport } from './routes/(private)/(operations)/layout'
import { Route as guestForgotPasswordPageRouteImport } from './routes/(guest)/forgot-password/page'
import { Route as guestLoginPageRouteImport } from './routes/(guest)/login/page'
import { Route as guestResetPasswordPageRouteImport } from './routes/(guest)/reset-password/page'
import { Route as privateoperationsSouscriptionLayoutRouteImport } from './routes/(private)/(operations)/souscription/layout'
import { Route as privateoperationsClientPortfolioPageRouteImport } from './routes/(private)/(operations)/client-portfolio/page'
import { Route as privateoperationsSouscriptionsPageRouteImport } from './routes/(private)/(operations)/souscriptions/page'
import { Route as privateoperationsSouscriptionIdPageRouteImport } from './routes/(private)/(operations)/souscription/$id/page'

const guestLayoutRoute = guestLayoutRouteImport.update({
  id: '/(guest)',
  getParentRoute: () => rootRouteImport,
} as any)
const privateLayoutRoute = privateLayoutRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const privatePageRoute = privatePageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => privateLayoutRoute,
} as any)
const privateoperationsLayoutRoute = privateoperationsLayoutRouteImport.update({
  id: '/(operations)',
  getParentRoute: () => privateLayoutRoute,
} as any)
const guestForgotPasswordPageRoute = guestForgotPasswordPageRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => guestLayoutRoute,
} as any)
const guestLoginPageRoute = guestLoginPageRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => guestLayoutRoute,
} as any)
const guestResetPasswordPageRoute = guestResetPasswordPageRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => guestLayoutRoute,
} as any)
const privateoperationsSouscriptionLayoutRoute =
  privateoperationsSouscriptionLayoutRouteImport.update({
    id: '/souscription',
    path: '/souscription',
    getParentRoute: () => privateoperationsLayoutRoute,
  } as any)
const privateoperationsClientPortfolioPageRoute =
  privateoperationsClientPortfolioPageRouteImport.update({
    id: '/client-portfolio/',
    path: '/client-portfolio/',
    getParentRoute: () => privateoperationsLayoutRoute,
  } as any)
const privateoperationsSouscriptionsPageRoute =
  privateoperationsSouscriptionsPageRouteImport.update({
    id: '/souscriptions/',
    path: '/souscriptions/',
    getParentRoute: () => privateoperationsLayoutRoute,
  } as any)
const privateoperationsSouscriptionIdPageRoute =
  privateoperationsSouscriptionIdPageRouteImport.update({
    id: '/$id/',
    path: '/$id/',
    getParentRoute: () => privateoperationsSouscriptionLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof privatePageRoute
  '/souscription': typeof privateoperationsSouscriptionLayoutRouteWithChildren
  '/forgot-password/': typeof guestForgotPasswordPageRoute
  '/login/': typeof guestLoginPageRoute
  '/reset-password/': typeof guestResetPasswordPageRoute
  '/client-portfolio/': typeof privateoperationsClientPortfolioPageRoute
  '/souscriptions/': typeof privateoperationsSouscriptionsPageRoute
  '/souscription/$id/': typeof privateoperationsSouscriptionIdPageRoute
}
export interface FileRoutesByTo {
  '/': typeof privatePageRoute
  '/souscription': typeof privateoperationsSouscriptionLayoutRouteWithChildren
  '/forgot-password': typeof guestForgotPasswordPageRoute
  '/login': typeof guestLoginPageRoute
  '/reset-password': typeof guestResetPasswordPageRoute
  '/client-portfolio': typeof privateoperationsClientPortfolioPageRoute
  '/souscriptions': typeof privateoperationsSouscriptionsPageRoute
  '/souscription/$id': typeof privateoperationsSouscriptionIdPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(guest)': typeof guestLayoutRouteWithChildren
  '/(private)': typeof privateLayoutRouteWithChildren
  '/(private)/(operations)': typeof privateoperationsLayoutRouteWithChildren
  '/(private)/': typeof privatePageRoute
  '/(private)/(operations)/souscription': typeof privateoperationsSouscriptionLayoutRouteWithChildren
  '/(guest)/forgot-password/': typeof guestForgotPasswordPageRoute
  '/(guest)/login/': typeof guestLoginPageRoute
  '/(guest)/reset-password/': typeof guestResetPasswordPageRoute
  '/(private)/(operations)/client-portfolio/': typeof privateoperationsClientPortfolioPageRoute
  '/(private)/(operations)/souscriptions/': typeof privateoperationsSouscriptionsPageRoute
  '/(private)/(operations)/souscription/$id/': typeof privateoperationsSouscriptionIdPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/souscription'
    | '/forgot-password/'
    | '/login/'
    | '/reset-password/'
    | '/client-portfolio/'
    | '/souscriptions/'
    | '/souscription/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/souscription'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/client-portfolio'
    | '/souscriptions'
    | '/souscription/$id'
  id:
    | '__root__'
    | '/(guest)'
    | '/(private)'
    | '/(private)/(operations)'
    | '/(private)/'
    | '/(private)/(operations)/souscription'
    | '/(guest)/forgot-password/'
    | '/(guest)/login/'
    | '/(guest)/reset-password/'
    | '/(private)/(operations)/client-portfolio/'
    | '/(private)/(operations)/souscriptions/'
    | '/(private)/(operations)/souscription/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  guestLayoutRoute: typeof guestLayoutRouteWithChildren
  privateLayoutRoute: typeof privateLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(guest)': {
      id: '/(guest)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof guestLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/': {
      id: '/(private)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof privatePageRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(private)/(operations)': {
      id: '/(private)/(operations)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateoperationsLayoutRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(guest)/forgot-password/': {
      id: '/(guest)/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof guestForgotPasswordPageRouteImport
      parentRoute: typeof guestLayoutRoute
    }
    '/(guest)/login/': {
      id: '/(guest)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof guestLoginPageRouteImport
      parentRoute: typeof guestLayoutRoute
    }
    '/(guest)/reset-password/': {
      id: '/(guest)/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof guestResetPasswordPageRouteImport
      parentRoute: typeof guestLayoutRoute
    }
    '/(private)/(operations)/souscription': {
      id: '/(private)/(operations)/souscription'
      path: '/souscription'
      fullPath: '/souscription'
      preLoaderRoute: typeof privateoperationsSouscriptionLayoutRouteImport
      parentRoute: typeof privateoperationsLayoutRoute
    }
    '/(private)/(operations)/client-portfolio/': {
      id: '/(private)/(operations)/client-portfolio/'
      path: '/client-portfolio'
      fullPath: '/client-portfolio/'
      preLoaderRoute: typeof privateoperationsClientPortfolioPageRouteImport
      parentRoute: typeof privateoperationsLayoutRoute
    }
    '/(private)/(operations)/souscriptions/': {
      id: '/(private)/(operations)/souscriptions/'
      path: '/souscriptions'
      fullPath: '/souscriptions/'
      preLoaderRoute: typeof privateoperationsSouscriptionsPageRouteImport
      parentRoute: typeof privateoperationsLayoutRoute
    }
    '/(private)/(operations)/souscription/$id/': {
      id: '/(private)/(operations)/souscription/$id/'
      path: '/$id'
      fullPath: '/souscription/$id/'
      preLoaderRoute: typeof privateoperationsSouscriptionIdPageRouteImport
      parentRoute: typeof privateoperationsSouscriptionLayoutRoute
    }
  }
}

interface guestLayoutRouteChildren {
  guestForgotPasswordPageRoute: typeof guestForgotPasswordPageRoute
  guestLoginPageRoute: typeof guestLoginPageRoute
  guestResetPasswordPageRoute: typeof guestResetPasswordPageRoute
}

const guestLayoutRouteChildren: guestLayoutRouteChildren = {
  guestForgotPasswordPageRoute: guestForgotPasswordPageRoute,
  guestLoginPageRoute: guestLoginPageRoute,
  guestResetPasswordPageRoute: guestResetPasswordPageRoute,
}

const guestLayoutRouteWithChildren = guestLayoutRoute._addFileChildren(
  guestLayoutRouteChildren,
)

interface privateoperationsSouscriptionLayoutRouteChildren {
  privateoperationsSouscriptionIdPageRoute: typeof privateoperationsSouscriptionIdPageRoute
}

const privateoperationsSouscriptionLayoutRouteChildren: privateoperationsSouscriptionLayoutRouteChildren =
  {
    privateoperationsSouscriptionIdPageRoute:
      privateoperationsSouscriptionIdPageRoute,
  }

const privateoperationsSouscriptionLayoutRouteWithChildren =
  privateoperationsSouscriptionLayoutRoute._addFileChildren(
    privateoperationsSouscriptionLayoutRouteChildren,
  )

interface privateoperationsLayoutRouteChildren {
  privateoperationsSouscriptionLayoutRoute: typeof privateoperationsSouscriptionLayoutRouteWithChildren
  privateoperationsClientPortfolioPageRoute: typeof privateoperationsClientPortfolioPageRoute
  privateoperationsSouscriptionsPageRoute: typeof privateoperationsSouscriptionsPageRoute
}

const privateoperationsLayoutRouteChildren: privateoperationsLayoutRouteChildren =
  {
    privateoperationsSouscriptionLayoutRoute:
      privateoperationsSouscriptionLayoutRouteWithChildren,
    privateoperationsClientPortfolioPageRoute:
      privateoperationsClientPortfolioPageRoute,
    privateoperationsSouscriptionsPageRoute:
      privateoperationsSouscriptionsPageRoute,
  }

const privateoperationsLayoutRouteWithChildren =
  privateoperationsLayoutRoute._addFileChildren(
    privateoperationsLayoutRouteChildren,
  )

interface privateLayoutRouteChildren {
  privateoperationsLayoutRoute: typeof privateoperationsLayoutRouteWithChildren
  privatePageRoute: typeof privatePageRoute
}

const privateLayoutRouteChildren: privateLayoutRouteChildren = {
  privateoperationsLayoutRoute: privateoperationsLayoutRouteWithChildren,
  privatePageRoute: privatePageRoute,
}

const privateLayoutRouteWithChildren = privateLayoutRoute._addFileChildren(
  privateLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  guestLayoutRoute: guestLayoutRouteWithChildren,
  privateLayoutRoute: privateLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
