/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as guestLayoutRouteImport } from './routes/(guest)/layout'
import { Route as protectedLayoutRouteImport } from './routes/(protected)/layout'
import { Route as protectedPageRouteImport } from './routes/(protected)/page'
import { Route as protectedoperationsLayoutRouteImport } from './routes/(protected)/(operations)/layout'
import { Route as guestForgotPasswordPageRouteImport } from './routes/(guest)/forgot-password/page'
import { Route as guestLoginPageRouteImport } from './routes/(guest)/login/page'
import { Route as guestResetPasswordPageRouteImport } from './routes/(guest)/reset-password/page'
import { Route as protectedoperationsSouscriptionLayoutRouteImport } from './routes/(protected)/(operations)/souscription/layout'
import { Route as protectedoperationsClientPortfolioPageRouteImport } from './routes/(protected)/(operations)/client-portfolio/page'
import { Route as protectedoperationsSouscriptionsPageRouteImport } from './routes/(protected)/(operations)/souscriptions/page'
import { Route as protectedoperationsSouscriptionIdPageRouteImport } from './routes/(protected)/(operations)/souscription/$id/page'

const guestLayoutRoute = guestLayoutRouteImport.update({
  id: '/(guest)',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedLayoutRoute = protectedLayoutRouteImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedPageRoute = protectedPageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => protectedLayoutRoute,
} as any)
const protectedoperationsLayoutRoute =
  protectedoperationsLayoutRouteImport.update({
    id: '/(operations)',
    getParentRoute: () => protectedLayoutRoute,
  } as any)
const guestForgotPasswordPageRoute = guestForgotPasswordPageRouteImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => guestLayoutRoute,
} as any)
const guestLoginPageRoute = guestLoginPageRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => guestLayoutRoute,
} as any)
const guestResetPasswordPageRoute = guestResetPasswordPageRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => guestLayoutRoute,
} as any)
const protectedoperationsSouscriptionLayoutRoute =
  protectedoperationsSouscriptionLayoutRouteImport.update({
    id: '/souscription',
    path: '/souscription',
    getParentRoute: () => protectedoperationsLayoutRoute,
  } as any)
const protectedoperationsClientPortfolioPageRoute =
  protectedoperationsClientPortfolioPageRouteImport.update({
    id: '/client-portfolio/',
    path: '/client-portfolio/',
    getParentRoute: () => protectedoperationsLayoutRoute,
  } as any)
const protectedoperationsSouscriptionsPageRoute =
  protectedoperationsSouscriptionsPageRouteImport.update({
    id: '/souscriptions/',
    path: '/souscriptions/',
    getParentRoute: () => protectedoperationsLayoutRoute,
  } as any)
const protectedoperationsSouscriptionIdPageRoute =
  protectedoperationsSouscriptionIdPageRouteImport.update({
    id: '/$id/',
    path: '/$id/',
    getParentRoute: () => protectedoperationsSouscriptionLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof protectedPageRoute
  '/souscription': typeof protectedoperationsSouscriptionLayoutRouteWithChildren
  '/forgot-password/': typeof guestForgotPasswordPageRoute
  '/login/': typeof guestLoginPageRoute
  '/reset-password/': typeof guestResetPasswordPageRoute
  '/client-portfolio/': typeof protectedoperationsClientPortfolioPageRoute
  '/souscriptions/': typeof protectedoperationsSouscriptionsPageRoute
  '/souscription/$id/': typeof protectedoperationsSouscriptionIdPageRoute
}
export interface FileRoutesByTo {
  '/': typeof protectedPageRoute
  '/souscription': typeof protectedoperationsSouscriptionLayoutRouteWithChildren
  '/forgot-password': typeof guestForgotPasswordPageRoute
  '/login': typeof guestLoginPageRoute
  '/reset-password': typeof guestResetPasswordPageRoute
  '/client-portfolio': typeof protectedoperationsClientPortfolioPageRoute
  '/souscriptions': typeof protectedoperationsSouscriptionsPageRoute
  '/souscription/$id': typeof protectedoperationsSouscriptionIdPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(guest)': typeof guestLayoutRouteWithChildren
  '/(protected)': typeof protectedLayoutRouteWithChildren
  '/(protected)/(operations)': typeof protectedoperationsLayoutRouteWithChildren
  '/(protected)/': typeof protectedPageRoute
  '/(protected)/(operations)/souscription': typeof protectedoperationsSouscriptionLayoutRouteWithChildren
  '/(guest)/forgot-password/': typeof guestForgotPasswordPageRoute
  '/(guest)/login/': typeof guestLoginPageRoute
  '/(guest)/reset-password/': typeof guestResetPasswordPageRoute
  '/(protected)/(operations)/client-portfolio/': typeof protectedoperationsClientPortfolioPageRoute
  '/(protected)/(operations)/souscriptions/': typeof protectedoperationsSouscriptionsPageRoute
  '/(protected)/(operations)/souscription/$id/': typeof protectedoperationsSouscriptionIdPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/souscription'
    | '/forgot-password/'
    | '/login/'
    | '/reset-password/'
    | '/client-portfolio/'
    | '/souscriptions/'
    | '/souscription/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/souscription'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/client-portfolio'
    | '/souscriptions'
    | '/souscription/$id'
  id:
    | '__root__'
    | '/(guest)'
    | '/(protected)'
    | '/(protected)/(operations)'
    | '/(protected)/'
    | '/(protected)/(operations)/souscription'
    | '/(guest)/forgot-password/'
    | '/(guest)/login/'
    | '/(guest)/reset-password/'
    | '/(protected)/(operations)/client-portfolio/'
    | '/(protected)/(operations)/souscriptions/'
    | '/(protected)/(operations)/souscription/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  guestLayoutRoute: typeof guestLayoutRouteWithChildren
  protectedLayoutRoute: typeof protectedLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(guest)': {
      id: '/(guest)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof guestLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)': {
      id: '/(protected)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/': {
      id: '/(protected)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedPageRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/(operations)': {
      id: '/(protected)/(operations)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedoperationsLayoutRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(guest)/forgot-password/': {
      id: '/(guest)/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof guestForgotPasswordPageRouteImport
      parentRoute: typeof guestLayoutRoute
    }
    '/(guest)/login/': {
      id: '/(guest)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof guestLoginPageRouteImport
      parentRoute: typeof guestLayoutRoute
    }
    '/(guest)/reset-password/': {
      id: '/(guest)/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof guestResetPasswordPageRouteImport
      parentRoute: typeof guestLayoutRoute
    }
    '/(protected)/(operations)/souscription': {
      id: '/(protected)/(operations)/souscription'
      path: '/souscription'
      fullPath: '/souscription'
      preLoaderRoute: typeof protectedoperationsSouscriptionLayoutRouteImport
      parentRoute: typeof protectedoperationsLayoutRoute
    }
    '/(protected)/(operations)/client-portfolio/': {
      id: '/(protected)/(operations)/client-portfolio/'
      path: '/client-portfolio'
      fullPath: '/client-portfolio/'
      preLoaderRoute: typeof protectedoperationsClientPortfolioPageRouteImport
      parentRoute: typeof protectedoperationsLayoutRoute
    }
    '/(protected)/(operations)/souscriptions/': {
      id: '/(protected)/(operations)/souscriptions/'
      path: '/souscriptions'
      fullPath: '/souscriptions/'
      preLoaderRoute: typeof protectedoperationsSouscriptionsPageRouteImport
      parentRoute: typeof protectedoperationsLayoutRoute
    }
    '/(protected)/(operations)/souscription/$id/': {
      id: '/(protected)/(operations)/souscription/$id/'
      path: '/$id'
      fullPath: '/souscription/$id/'
      preLoaderRoute: typeof protectedoperationsSouscriptionIdPageRouteImport
      parentRoute: typeof protectedoperationsSouscriptionLayoutRoute
    }
  }
}

interface guestLayoutRouteChildren {
  guestForgotPasswordPageRoute: typeof guestForgotPasswordPageRoute
  guestLoginPageRoute: typeof guestLoginPageRoute
  guestResetPasswordPageRoute: typeof guestResetPasswordPageRoute
}

const guestLayoutRouteChildren: guestLayoutRouteChildren = {
  guestForgotPasswordPageRoute: guestForgotPasswordPageRoute,
  guestLoginPageRoute: guestLoginPageRoute,
  guestResetPasswordPageRoute: guestResetPasswordPageRoute,
}

const guestLayoutRouteWithChildren = guestLayoutRoute._addFileChildren(
  guestLayoutRouteChildren,
)

interface protectedoperationsSouscriptionLayoutRouteChildren {
  protectedoperationsSouscriptionIdPageRoute: typeof protectedoperationsSouscriptionIdPageRoute
}

const protectedoperationsSouscriptionLayoutRouteChildren: protectedoperationsSouscriptionLayoutRouteChildren =
  {
    protectedoperationsSouscriptionIdPageRoute:
      protectedoperationsSouscriptionIdPageRoute,
  }

const protectedoperationsSouscriptionLayoutRouteWithChildren =
  protectedoperationsSouscriptionLayoutRoute._addFileChildren(
    protectedoperationsSouscriptionLayoutRouteChildren,
  )

interface protectedoperationsLayoutRouteChildren {
  protectedoperationsSouscriptionLayoutRoute: typeof protectedoperationsSouscriptionLayoutRouteWithChildren
  protectedoperationsClientPortfolioPageRoute: typeof protectedoperationsClientPortfolioPageRoute
  protectedoperationsSouscriptionsPageRoute: typeof protectedoperationsSouscriptionsPageRoute
}

const protectedoperationsLayoutRouteChildren: protectedoperationsLayoutRouteChildren =
  {
    protectedoperationsSouscriptionLayoutRoute:
      protectedoperationsSouscriptionLayoutRouteWithChildren,
    protectedoperationsClientPortfolioPageRoute:
      protectedoperationsClientPortfolioPageRoute,
    protectedoperationsSouscriptionsPageRoute:
      protectedoperationsSouscriptionsPageRoute,
  }

const protectedoperationsLayoutRouteWithChildren =
  protectedoperationsLayoutRoute._addFileChildren(
    protectedoperationsLayoutRouteChildren,
  )

interface protectedLayoutRouteChildren {
  protectedoperationsLayoutRoute: typeof protectedoperationsLayoutRouteWithChildren
  protectedPageRoute: typeof protectedPageRoute
}

const protectedLayoutRouteChildren: protectedLayoutRouteChildren = {
  protectedoperationsLayoutRoute: protectedoperationsLayoutRouteWithChildren,
  protectedPageRoute: protectedPageRoute,
}

const protectedLayoutRouteWithChildren = protectedLayoutRoute._addFileChildren(
  protectedLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  guestLayoutRoute: guestLayoutRouteWithChildren,
  protectedLayoutRoute: protectedLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
