/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as privateLayoutRouteImport } from './routes/(private)/layout'
import { Route as guestauthLayoutRouteImport } from './routes/(guest)/(auth)/layout'
import { Route as privatePageRouteImport } from './routes/(private)/page'
import { Route as privateoperationsLayoutRouteImport } from './routes/(private)/(operations)/layout'
import { Route as privateProfileLayoutRouteImport } from './routes/(private)/profile/layout'
import { Route as privateoperationsSouscriptionLayoutRouteImport } from './routes/(private)/(operations)/souscription/layout'
import { Route as privateProfilePageRouteImport } from './routes/(private)/profile/page'
import { Route as guestauthActivateAccountPageRouteImport } from './routes/(guest)/(auth)/activate-account/page'
import { Route as guestauthForgotPasswordPageRouteImport } from './routes/(guest)/(auth)/forgot-password/page'
import { Route as guestauthLoginPageRouteImport } from './routes/(guest)/(auth)/login/page'
import { Route as guestauthResetPasswordPageRouteImport } from './routes/(guest)/(auth)/reset-password/page'
import { Route as privateoperationsClientPortfolioPageRouteImport } from './routes/(private)/(operations)/client-portfolio/page'
import { Route as privateoperationsSouscriptionsPageRouteImport } from './routes/(private)/(operations)/souscriptions/page'
import { Route as privateProfilePrivacyPageRouteImport } from './routes/(private)/profile/privacy/page'
import { Route as privateProfileSecurityPageRouteImport } from './routes/(private)/profile/security/page'
import { Route as privateoperationsSouscriptionIdPageRouteImport } from './routes/(private)/(operations)/souscription/$id/page'

const privateLayoutRoute = privateLayoutRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const guestauthLayoutRoute = guestauthLayoutRouteImport.update({
  id: '/(guest)/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const privatePageRoute = privatePageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => privateLayoutRoute,
} as any)
const privateoperationsLayoutRoute = privateoperationsLayoutRouteImport.update({
  id: '/(operations)',
  getParentRoute: () => privateLayoutRoute,
} as any)
const privateProfileLayoutRoute = privateProfileLayoutRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => privateLayoutRoute,
} as any)
const privateoperationsSouscriptionLayoutRoute =
  privateoperationsSouscriptionLayoutRouteImport.update({
    id: '/souscription',
    path: '/souscription',
    getParentRoute: () => privateoperationsLayoutRoute,
  } as any)
const privateProfilePageRoute = privateProfilePageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => privateProfileLayoutRoute,
} as any)
const guestauthActivateAccountPageRoute =
  guestauthActivateAccountPageRouteImport.update({
    id: '/activate-account/',
    path: '/activate-account/',
    getParentRoute: () => guestauthLayoutRoute,
  } as any)
const guestauthForgotPasswordPageRoute =
  guestauthForgotPasswordPageRouteImport.update({
    id: '/forgot-password/',
    path: '/forgot-password/',
    getParentRoute: () => guestauthLayoutRoute,
  } as any)
const guestauthLoginPageRoute = guestauthLoginPageRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => guestauthLayoutRoute,
} as any)
const guestauthResetPasswordPageRoute =
  guestauthResetPasswordPageRouteImport.update({
    id: '/reset-password/',
    path: '/reset-password/',
    getParentRoute: () => guestauthLayoutRoute,
  } as any)
const privateoperationsClientPortfolioPageRoute =
  privateoperationsClientPortfolioPageRouteImport.update({
    id: '/client-portfolio/',
    path: '/client-portfolio/',
    getParentRoute: () => privateoperationsLayoutRoute,
  } as any)
const privateoperationsSouscriptionsPageRoute =
  privateoperationsSouscriptionsPageRouteImport.update({
    id: '/souscriptions/',
    path: '/souscriptions/',
    getParentRoute: () => privateoperationsLayoutRoute,
  } as any)
const privateProfilePrivacyPageRoute =
  privateProfilePrivacyPageRouteImport.update({
    id: '/privacy/',
    path: '/privacy/',
    getParentRoute: () => privateProfileLayoutRoute,
  } as any)
const privateProfileSecurityPageRoute =
  privateProfileSecurityPageRouteImport.update({
    id: '/security/',
    path: '/security/',
    getParentRoute: () => privateProfileLayoutRoute,
  } as any)
const privateoperationsSouscriptionIdPageRoute =
  privateoperationsSouscriptionIdPageRouteImport.update({
    id: '/$id/',
    path: '/$id/',
    getParentRoute: () => privateoperationsSouscriptionLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/profile': typeof privateProfileLayoutRouteWithChildren
  '/': typeof privatePageRoute
  '/souscription': typeof privateoperationsSouscriptionLayoutRouteWithChildren
  '/profile/': typeof privateProfilePageRoute
  '/activate-account/': typeof guestauthActivateAccountPageRoute
  '/forgot-password/': typeof guestauthForgotPasswordPageRoute
  '/login/': typeof guestauthLoginPageRoute
  '/reset-password/': typeof guestauthResetPasswordPageRoute
  '/client-portfolio/': typeof privateoperationsClientPortfolioPageRoute
  '/souscriptions/': typeof privateoperationsSouscriptionsPageRoute
  '/profile/privacy/': typeof privateProfilePrivacyPageRoute
  '/profile/security/': typeof privateProfileSecurityPageRoute
  '/souscription/$id/': typeof privateoperationsSouscriptionIdPageRoute
}
export interface FileRoutesByTo {
  '/': typeof privatePageRoute
  '/souscription': typeof privateoperationsSouscriptionLayoutRouteWithChildren
  '/profile': typeof privateProfilePageRoute
  '/activate-account': typeof guestauthActivateAccountPageRoute
  '/forgot-password': typeof guestauthForgotPasswordPageRoute
  '/login': typeof guestauthLoginPageRoute
  '/reset-password': typeof guestauthResetPasswordPageRoute
  '/client-portfolio': typeof privateoperationsClientPortfolioPageRoute
  '/souscriptions': typeof privateoperationsSouscriptionsPageRoute
  '/profile/privacy': typeof privateProfilePrivacyPageRoute
  '/profile/security': typeof privateProfileSecurityPageRoute
  '/souscription/$id': typeof privateoperationsSouscriptionIdPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(private)': typeof privateLayoutRouteWithChildren
  '/(guest)/(auth)': typeof guestauthLayoutRouteWithChildren
  '/(private)/(operations)': typeof privateoperationsLayoutRouteWithChildren
  '/(private)/profile': typeof privateProfileLayoutRouteWithChildren
  '/(private)/': typeof privatePageRoute
  '/(private)/(operations)/souscription': typeof privateoperationsSouscriptionLayoutRouteWithChildren
  '/(private)/profile/': typeof privateProfilePageRoute
  '/(guest)/(auth)/activate-account/': typeof guestauthActivateAccountPageRoute
  '/(guest)/(auth)/forgot-password/': typeof guestauthForgotPasswordPageRoute
  '/(guest)/(auth)/login/': typeof guestauthLoginPageRoute
  '/(guest)/(auth)/reset-password/': typeof guestauthResetPasswordPageRoute
  '/(private)/(operations)/client-portfolio/': typeof privateoperationsClientPortfolioPageRoute
  '/(private)/(operations)/souscriptions/': typeof privateoperationsSouscriptionsPageRoute
  '/(private)/profile/privacy/': typeof privateProfilePrivacyPageRoute
  '/(private)/profile/security/': typeof privateProfileSecurityPageRoute
  '/(private)/(operations)/souscription/$id/': typeof privateoperationsSouscriptionIdPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/profile'
    | '/'
    | '/souscription'
    | '/profile/'
    | '/activate-account/'
    | '/forgot-password/'
    | '/login/'
    | '/reset-password/'
    | '/client-portfolio/'
    | '/souscriptions/'
    | '/profile/privacy/'
    | '/profile/security/'
    | '/souscription/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/souscription'
    | '/profile'
    | '/activate-account'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/client-portfolio'
    | '/souscriptions'
    | '/profile/privacy'
    | '/profile/security'
    | '/souscription/$id'
  id:
    | '__root__'
    | '/(private)'
    | '/(guest)/(auth)'
    | '/(private)/(operations)'
    | '/(private)/profile'
    | '/(private)/'
    | '/(private)/(operations)/souscription'
    | '/(private)/profile/'
    | '/(guest)/(auth)/activate-account/'
    | '/(guest)/(auth)/forgot-password/'
    | '/(guest)/(auth)/login/'
    | '/(guest)/(auth)/reset-password/'
    | '/(private)/(operations)/client-portfolio/'
    | '/(private)/(operations)/souscriptions/'
    | '/(private)/profile/privacy/'
    | '/(private)/profile/security/'
    | '/(private)/(operations)/souscription/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  privateLayoutRoute: typeof privateLayoutRouteWithChildren
  guestauthLayoutRoute: typeof guestauthLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(guest)/(auth)': {
      id: '/(guest)/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof guestauthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)/': {
      id: '/(private)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof privatePageRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(private)/(operations)': {
      id: '/(private)/(operations)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateoperationsLayoutRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(private)/profile': {
      id: '/(private)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof privateProfileLayoutRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(private)/(operations)/souscription': {
      id: '/(private)/(operations)/souscription'
      path: '/souscription'
      fullPath: '/souscription'
      preLoaderRoute: typeof privateoperationsSouscriptionLayoutRouteImport
      parentRoute: typeof privateoperationsLayoutRoute
    }
    '/(private)/profile/': {
      id: '/(private)/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof privateProfilePageRouteImport
      parentRoute: typeof privateProfileLayoutRoute
    }
    '/(guest)/(auth)/activate-account/': {
      id: '/(guest)/(auth)/activate-account/'
      path: '/activate-account'
      fullPath: '/activate-account/'
      preLoaderRoute: typeof guestauthActivateAccountPageRouteImport
      parentRoute: typeof guestauthLayoutRoute
    }
    '/(guest)/(auth)/forgot-password/': {
      id: '/(guest)/(auth)/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof guestauthForgotPasswordPageRouteImport
      parentRoute: typeof guestauthLayoutRoute
    }
    '/(guest)/(auth)/login/': {
      id: '/(guest)/(auth)/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof guestauthLoginPageRouteImport
      parentRoute: typeof guestauthLayoutRoute
    }
    '/(guest)/(auth)/reset-password/': {
      id: '/(guest)/(auth)/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof guestauthResetPasswordPageRouteImport
      parentRoute: typeof guestauthLayoutRoute
    }
    '/(private)/(operations)/client-portfolio/': {
      id: '/(private)/(operations)/client-portfolio/'
      path: '/client-portfolio'
      fullPath: '/client-portfolio/'
      preLoaderRoute: typeof privateoperationsClientPortfolioPageRouteImport
      parentRoute: typeof privateoperationsLayoutRoute
    }
    '/(private)/(operations)/souscriptions/': {
      id: '/(private)/(operations)/souscriptions/'
      path: '/souscriptions'
      fullPath: '/souscriptions/'
      preLoaderRoute: typeof privateoperationsSouscriptionsPageRouteImport
      parentRoute: typeof privateoperationsLayoutRoute
    }
    '/(private)/profile/privacy/': {
      id: '/(private)/profile/privacy/'
      path: '/privacy'
      fullPath: '/profile/privacy/'
      preLoaderRoute: typeof privateProfilePrivacyPageRouteImport
      parentRoute: typeof privateProfileLayoutRoute
    }
    '/(private)/profile/security/': {
      id: '/(private)/profile/security/'
      path: '/security'
      fullPath: '/profile/security/'
      preLoaderRoute: typeof privateProfileSecurityPageRouteImport
      parentRoute: typeof privateProfileLayoutRoute
    }
    '/(private)/(operations)/souscription/$id/': {
      id: '/(private)/(operations)/souscription/$id/'
      path: '/$id'
      fullPath: '/souscription/$id/'
      preLoaderRoute: typeof privateoperationsSouscriptionIdPageRouteImport
      parentRoute: typeof privateoperationsSouscriptionLayoutRoute
    }
  }
}

interface privateoperationsSouscriptionLayoutRouteChildren {
  privateoperationsSouscriptionIdPageRoute: typeof privateoperationsSouscriptionIdPageRoute
}

const privateoperationsSouscriptionLayoutRouteChildren: privateoperationsSouscriptionLayoutRouteChildren =
  {
    privateoperationsSouscriptionIdPageRoute:
      privateoperationsSouscriptionIdPageRoute,
  }

const privateoperationsSouscriptionLayoutRouteWithChildren =
  privateoperationsSouscriptionLayoutRoute._addFileChildren(
    privateoperationsSouscriptionLayoutRouteChildren,
  )

interface privateoperationsLayoutRouteChildren {
  privateoperationsSouscriptionLayoutRoute: typeof privateoperationsSouscriptionLayoutRouteWithChildren
  privateoperationsClientPortfolioPageRoute: typeof privateoperationsClientPortfolioPageRoute
  privateoperationsSouscriptionsPageRoute: typeof privateoperationsSouscriptionsPageRoute
}

const privateoperationsLayoutRouteChildren: privateoperationsLayoutRouteChildren =
  {
    privateoperationsSouscriptionLayoutRoute:
      privateoperationsSouscriptionLayoutRouteWithChildren,
    privateoperationsClientPortfolioPageRoute:
      privateoperationsClientPortfolioPageRoute,
    privateoperationsSouscriptionsPageRoute:
      privateoperationsSouscriptionsPageRoute,
  }

const privateoperationsLayoutRouteWithChildren =
  privateoperationsLayoutRoute._addFileChildren(
    privateoperationsLayoutRouteChildren,
  )

interface privateProfileLayoutRouteChildren {
  privateProfilePageRoute: typeof privateProfilePageRoute
  privateProfilePrivacyPageRoute: typeof privateProfilePrivacyPageRoute
  privateProfileSecurityPageRoute: typeof privateProfileSecurityPageRoute
}

const privateProfileLayoutRouteChildren: privateProfileLayoutRouteChildren = {
  privateProfilePageRoute: privateProfilePageRoute,
  privateProfilePrivacyPageRoute: privateProfilePrivacyPageRoute,
  privateProfileSecurityPageRoute: privateProfileSecurityPageRoute,
}

const privateProfileLayoutRouteWithChildren =
  privateProfileLayoutRoute._addFileChildren(privateProfileLayoutRouteChildren)

interface privateLayoutRouteChildren {
  privateoperationsLayoutRoute: typeof privateoperationsLayoutRouteWithChildren
  privateProfileLayoutRoute: typeof privateProfileLayoutRouteWithChildren
  privatePageRoute: typeof privatePageRoute
}

const privateLayoutRouteChildren: privateLayoutRouteChildren = {
  privateoperationsLayoutRoute: privateoperationsLayoutRouteWithChildren,
  privateProfileLayoutRoute: privateProfileLayoutRouteWithChildren,
  privatePageRoute: privatePageRoute,
}

const privateLayoutRouteWithChildren = privateLayoutRoute._addFileChildren(
  privateLayoutRouteChildren,
)

interface guestauthLayoutRouteChildren {
  guestauthActivateAccountPageRoute: typeof guestauthActivateAccountPageRoute
  guestauthForgotPasswordPageRoute: typeof guestauthForgotPasswordPageRoute
  guestauthLoginPageRoute: typeof guestauthLoginPageRoute
  guestauthResetPasswordPageRoute: typeof guestauthResetPasswordPageRoute
}

const guestauthLayoutRouteChildren: guestauthLayoutRouteChildren = {
  guestauthActivateAccountPageRoute: guestauthActivateAccountPageRoute,
  guestauthForgotPasswordPageRoute: guestauthForgotPasswordPageRoute,
  guestauthLoginPageRoute: guestauthLoginPageRoute,
  guestauthResetPasswordPageRoute: guestauthResetPasswordPageRoute,
}

const guestauthLayoutRouteWithChildren = guestauthLayoutRoute._addFileChildren(
  guestauthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  privateLayoutRoute: privateLayoutRouteWithChildren,
  guestauthLayoutRoute: guestauthLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
