/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  features: {
    admin: {
      adminManagement: {
        admins: {
          Create: () => import('#src/features/admin/admin_management/admins/controllers/create.controller'),
          List: () => import('#src/features/admin/admin_management/admins/controllers/list.controller'),
          View: () => import('#src/features/admin/admin_management/admins/controllers/view.controller'),
        },
        authentication: {
          Login: () => import('#src/features/admin/admin_management/authentication/controllers/login.controller'),
          Logout: () => import('#src/features/admin/admin_management/authentication/controllers/logout.controller'),
        },
        password: {
          Forgot: () => import('#src/features/admin/admin_management/password/controllers/forgot.controller'),
          Reset: () => import('#src/features/admin/admin_management/password/controllers/reset.controller'),
        },
        profile: {
          View: () => import('#src/features/admin/admin_management/profile/controllers/view.controller'),
        },
      },
    },
    client: {
      userManagement: {
        authentication: {
          Login: () => import('#src/features/client/user_management/authentication/controllers/login.controller'),
          Logout: () => import('#src/features/client/user_management/authentication/controllers/logout.controller'),
        },
        password: {
          Forgot: () => import('#src/features/client/user_management/password/controllers/forgot.controller'),
          Reset: () => import('#src/features/client/user_management/password/controllers/reset.controller'),
          Update: () => import('#src/features/client/user_management/password/controllers/update.controller'),
        },
        profile: {
          Delete: () => import('#src/features/client/user_management/profile/controllers/delete.controller'),
          Update: () => import('#src/features/client/user_management/profile/controllers/update.controller'),
          View: () => import('#src/features/client/user_management/profile/controllers/view.controller'),
        },
      },
    },
  },
}
