/**
* This file is automatically generated.
* DO NOT EDIT manually
*/
/// <reference path="./manifest.d.ts" />

export type Address = Awaited<ReturnType<typeof import("#presenters/address.presenter").default.prototype.toJSON>>;

export type Admin = Awaited<ReturnType<typeof import("#presenters/admin.presenter").default.prototype.toJSON>>;

export type File = Awaited<ReturnType<typeof import("#presenters/file.presenter").default.prototype.toJSON>>;

export type Firm = Awaited<ReturnType<typeof import("#presenters/firm.presenter").default.prototype.toJSON>>;

export type Network = Awaited<ReturnType<typeof import("#presenters/network.presenter").default.prototype.toJSON>>;

export type Pagination = Awaited<ReturnType<typeof import("#presenters/pagination.presenter").default.prototype.toJSON>>;

export type PaymentDetail = Awaited<ReturnType<typeof import("#presenters/payment_detail.presenter").default.prototype.toJSON>>;

export type User = Awaited<ReturnType<typeof import("#presenters/user.presenter").default.prototype.toJSON>>;

export type Company = Awaited<ReturnType<typeof import("#presenters/company.presenter").default.prototype.toJSON>>;

export type CompanyContact = Awaited<ReturnType<typeof import("#presenters/company_contact.presenter").default.prototype.toJSON>>;

export type Contact = Awaited<ReturnType<typeof import("#presenters/contact.presenter").default.prototype.toJSON>>;

export type Subscription = Awaited<ReturnType<typeof import("#presenters/subscription.presenter").default.prototype.toJSON>>;
