/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AddressSchema extends BaseModel {
  static $columns = ['city', 'coordinates', 'createdAt', 'id', 'lineOne', 'lineTwo', 'updatedAt', 'zip'] as const
  $columns = AddressSchema.$columns
  @column()
  declare city: string
  @column()
  declare coordinates: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lineOne: string
  @column()
  declare lineTwo: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare zip: string
}

export class AdminSchema extends BaseModel {
  static $columns = ['activatedAt', 'createdAt', 'email', 'id', 'name', 'password', 'updatedAt'] as const
  $columns = AdminSchema.$columns
  @column.dateTime()
  declare activatedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class FileSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'key', 'name', 'size', 'type', 'updatedAt'] as const
  $columns = FileSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare key: string
  @column()
  declare name: string
  @column()
  declare size: number
  @column()
  declare type: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class FirmSchema extends BaseModel {
  static $columns = ['addressId', 'amundiOrgId', 'createdAt', 'id', 'name', 'networkId', 'orias', 'paymentDetailId', 'updatedAt'] as const
  $columns = FirmSchema.$columns
  @column()
  declare addressId: number
  @column()
  declare amundiOrgId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare networkId: number | null
  @column()
  declare orias: string
  @column()
  declare paymentDetailId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class NetworkSchema extends BaseModel {
  static $columns = ['addressId', 'amundiOrgId', 'createdAt', 'goCode', 'id', 'name', 'paymentDetailId', 'updatedAt'] as const
  $columns = NetworkSchema.$columns
  @column()
  declare addressId: number
  @column()
  declare amundiOrgId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare goCode: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare paymentDetailId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PaymentDetailSchema extends BaseModel {
  static $columns = ['bic', 'createdAt', 'iban', 'id', 'updatedAt'] as const
  $columns = PaymentDetailSchema.$columns
  @column()
  declare bic: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare iban: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'firstName', 'id', 'lastName', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare firstName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastName: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
