/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AddressSchema extends BaseModel {
  static $columns = ['city', 'coordinates', 'createdAt', 'id', 'lineOne', 'lineTwo', 'updatedAt', 'zip'] as const
  $columns = AddressSchema.$columns
  @column()
  declare city: string
  @column()
  declare coordinates: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lineOne: string
  @column()
  declare lineTwo: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare zip: string
}

export class AdminSchema extends BaseModel {
  static $columns = ['activatedAt', 'createdAt', 'email', 'id', 'name', 'password', 'updatedAt'] as const
  $columns = AdminSchema.$columns
  @column.dateTime()
  declare activatedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class CompanySchema extends BaseModel {
  static $columns = ['addressId', 'bankDetailsDocumentId', 'companyCorrespondentId', 'companyDetailsDocumentId', 'companyHeadcount', 'companyLegalAgentId', 'contactsStatusDocumentId', 'createdAt', 'financialYearClosingDay', 'id', 'legalAgentIdDocumentId', 'legalForm', 'naf', 'name', 'paymentDetailId', 'siren', 'siret', 'subscriptionId', 'updatedAt', 'vatNumber'] as const
  $columns = CompanySchema.$columns
  @column()
  declare addressId: number | null
  @column()
  declare bankDetailsDocumentId: number | null
  @column()
  declare companyCorrespondentId: number | null
  @column()
  declare companyDetailsDocumentId: number | null
  @column()
  declare companyHeadcount: string | null
  @column()
  declare companyLegalAgentId: number | null
  @column()
  declare contactsStatusDocumentId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare financialYearClosingDay: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare legalAgentIdDocumentId: number | null
  @column()
  declare legalForm: number | null
  @column()
  declare naf: string | null
  @column()
  declare name: string | null
  @column()
  declare paymentDetailId: number | null
  @column()
  declare siren: string | null
  @column()
  declare siret: string | null
  @column()
  declare subscriptionId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare vatNumber: string | null
}

export class CompanyContactSchema extends BaseModel {
  static $columns = ['companyId', 'contactId', 'id'] as const
  $columns = CompanyContactSchema.$columns
  @column()
  declare companyId: number | null
  @column()
  declare contactId: number | null
  @column({ isPrimary: true })
  declare id: number
}

export class ContactSchema extends BaseModel {
  static $columns = ['amundiPortalId', 'authorizations', 'createdAt', 'email', 'firstName', 'function', 'id', 'isSameAsLegal', 'isSignatoryOnKbis', 'kind', 'lastName', 'legalName', 'phoneNumber', 'updatedAt'] as const
  $columns = ContactSchema.$columns
  @column()
  declare amundiPortalId: string | null
  @column()
  declare authorizations: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column()
  declare firstName: string | null
  @column()
  declare function: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isSameAsLegal: boolean | null
  @column()
  declare isSignatoryOnKbis: boolean | null
  @column()
  declare kind: number | null
  @column()
  declare lastName: string | null
  @column()
  declare legalName: string | null
  @column()
  declare phoneNumber: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class FileSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'key', 'name', 'size', 'type', 'updatedAt'] as const
  $columns = FileSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare key: string
  @column()
  declare name: string
  @column()
  declare size: number
  @column()
  declare type: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class FirmSchema extends BaseModel {
  static $columns = ['addressId', 'amundiOrgId', 'createdAt', 'id', 'name', 'networkId', 'orias', 'paymentDetailId', 'updatedAt'] as const
  $columns = FirmSchema.$columns
  @column()
  declare addressId: number
  @column()
  declare amundiOrgId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare networkId: number | null
  @column()
  declare orias: string
  @column()
  declare paymentDetailId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class NetworkSchema extends BaseModel {
  static $columns = ['addressId', 'amundiOrgId', 'createdAt', 'goCode', 'id', 'name', 'paymentDetailId', 'updatedAt'] as const
  $columns = NetworkSchema.$columns
  @column()
  declare addressId: number
  @column()
  declare amundiOrgId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare goCode: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare paymentDetailId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class PaymentDetailSchema extends BaseModel {
  static $columns = ['bic', 'createdAt', 'iban', 'id', 'updatedAt'] as const
  $columns = PaymentDetailSchema.$columns
  @column()
  declare bic: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare iban: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class SubscriptionSchema extends BaseModel {
  static $columns = ['approvedAt', 'completedAt', 'completedSteps', 'createdAt', 'createdBy', 'id', 'status', 'statusUpdatedAt', 'submittedAt', 'updatedAt'] as const
  $columns = SubscriptionSchema.$columns
  @column.dateTime()
  declare approvedAt: DateTime | null
  @column.dateTime()
  declare completedAt: DateTime | null
  @column()
  declare completedSteps: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdBy: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare status: number
  @column.dateTime()
  declare statusUpdatedAt: DateTime | null
  @column.dateTime()
  declare submittedAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'firstName', 'id', 'lastName', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare firstName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lastName: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}
